function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 22-Nov-2016 19:16:53

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

% Create xlabel
xlabel('H_{cresta} (A/m)','FontWeight','bold','FontSize',11);

% Create title
title('Ciclo dinámico para un B_{cresta} de 1.5 T  a 50 Hz','FontSize',11);

% Create ylabel
ylabel('B_{cresta} (T)','FontWeight','bold','FontSize',11);

grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'GridColor',[0 0.450980392156863 0.741176470588235],...
    'XAxisLocation','origin','YAxisLocation','origin');
