function createfigure(X1, Y1, C1, X2, C2)
%CREATEFIGURE(X1, Y1, C1, X2, C2)
%  X1:  scatter x
%  Y1:  scatter y
%  C1:  scatter c
%  X2:  scatter x
%  C2:  scatter c

%  Auto-generated by MATLAB on 22-Nov-2016 19:10:23

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,C1,'DisplayName','H_{ef}-B_{cresta}',...
    'MarkerFaceColor',[0 0.498039215803146 0],...
    'MarkerEdgeColor',[0 0.498039215803146 0]);

% Create scatter
scatter(X2,Y1,C2,'DisplayName','H_{cresta}-B_{cresta}',...
    'MarkerFaceColor',[0 0.447058826684952 0.74117648601532],...
    'MarkerEdgeColor',[0 0.447058826684952 0.74117648601532]);

% Create xlabel
xlabel({'H (A/m)'},'FontWeight','bold');

% Create title
title({'H_{ef}-B_{cresta} & H_{cresta}-B_{cresta}'});

% Create ylabel
ylabel({'B_{cresta} (T)'},'FontWeight','bold');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'GridAlpha',0.25,'GridColor',...
    [0 0.450980392156863 0.741176470588235],'GridLineStyle','--');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northwest');

