function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 13-Oct-2016 21:06:59

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','CH1','LineWidth',2,'Color',[0 0 1]);

% Create xlabel
xlabel('t(ms)','FontSize',11);

% Create title
title({'Transitorio de descarga de un Condensador 50 \muF (\tau=40 ms)'},...
    'FontSize',11);

% Create ylabel
ylabel({'U(V)'},'FontSize',11,'Color',[0 0 1]);

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'GridAlpha',1,'GridLineStyle','--','LineWidth',1);
% Create legend
legend(axes1,'show');

