function createfigure(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 13-Oct-2016 20:47:36

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create plot
plot(X1,Y1,'DisplayName','CH1 (I)','LineWidth',2,'LineStyle','--',...
    'Color',[0 0 1]);

% Create ylabel
ylabel({'CH1, U(V)'},'FontSize',11);

% Set the remaining axes properties
set(axes1,'YColor',[0 0 1]);
Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.5 0.5]);
% Activate the right side of the axes
yyaxis(axes1,'right');
% Create plot
plot(X1,Y2,'DisplayName','CH2 (U)','LineWidth',2,...
    'Color',[0 0.498039215803146 0]);

% Create ylabel
ylabel('CH2, U(V)','FontSize',11);

% Set the remaining axes properties
set(axes1,'YColor',[0 0.5 0]);
% Create xlabel
xlabel('t(ms)','FontSize',11);

% Create title
title({''},'FontSize',11);

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'GridAlpha',1,'GridColor',[0 0 1],'GridLineStyle','--',...
    'LineWidth',1,'MinorGridColor',[0 0 1],'XColor',[0 0 0],'ZColor',[0 0 0]);
% Create legend
legend(axes1,'show');

